name: Deploy project
on: [push]
jobs:
  db:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: liquibase-github-actions/update@v4.19.0
      with:
        changelogFile: "migrations-sqlite/changelog1.sql"
        url: "jdbc:sqlite:migrations-sqlite/example.db"
        headless: true
        logLevel: INFO