name: Deploy project
on: [push]
jobs:
  db:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: liquibase-github-actions/update@v4.19.0
      with:
        changelogFile: "migrations-sqlite/changelog.sql"
        url: "jdbc:sqlite:migrations-sqlite/example.db"
        headless: true
        logLevel: INFO
    - name: Commit files
      run: |
        git config --local user.email "sergio@giraldo.com.br"
        git config --local user.name "Sergio Rodrigues Giraldo"
        git add .
        git commit -m "Add changes"
        git push origin HEAD:main